### ISSUE TITLE
Warning - std_tools

### ISSUE THREAD

**Issue by khoramshahi** [epfl-lasa/robot-toolkit#9]
catkin_package() DEPENDS on 'ncurses' but neither 'ncurses_INCLUDE_DIRS'
  nor 'ncurses_LIBRARIES' is defined.

**Comment by gpldecha** [comment]
Ncurser library does not provide the definitions of those variables. just
have to install it.
https://www.cyberciti.biz/faq/linux-install-ncurses-library-headers-on-debian-ubuntu-centos-fedora/

**Comment by khoramshahi** [comment]
thanks @gpldecha, I am closing this issue.
I also updated the readme file.
